// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonDraft.Data;

#nullable disable

namespace PokemonDraft.Migrations
{
    [DbContext(typeof(PokemonDraftContext))]
    [Migration("20241112201122_user account with policies")]
    partial class useraccountwithpolicies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokemonDraft.Models.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("user_account");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "guest1",
                            UserName = "guest"
                        },
                        new
                        {
                            Id = 2,
                            Password = "player1",
                            UserName = "player"
                        },
                        new
                        {
                            Id = 3,
                            Password = "admin1",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("PokemonDraft.Models.Entities.UserAccountPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("is_enabled");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int")
                        .HasColumnName("user_account_id");

                    b.Property<string>("UserPolicy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_policy");

                    b.HasKey("Id");

                    b.ToTable("user_account_policy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsEnabled = false,
                            UserAccountId = 1,
                            UserPolicy = "VIEW_PRODUCT"
                        },
                        new
                        {
                            Id = 2,
                            IsEnabled = false,
                            UserAccountId = 1,
                            UserPolicy = "ADD_PRODUCT"
                        },
                        new
                        {
                            Id = 3,
                            IsEnabled = false,
                            UserAccountId = 1,
                            UserPolicy = "EDIT PRODUCT"
                        },
                        new
                        {
                            Id = 4,
                            IsEnabled = false,
                            UserAccountId = 1,
                            UserPolicy = "DELETE_PRODUCT"
                        },
                        new
                        {
                            Id = 5,
                            IsEnabled = true,
                            UserAccountId = 2,
                            UserPolicy = "VIEW_PRODUCT"
                        },
                        new
                        {
                            Id = 6,
                            IsEnabled = false,
                            UserAccountId = 2,
                            UserPolicy = "ADD_PRODUCT"
                        },
                        new
                        {
                            Id = 7,
                            IsEnabled = false,
                            UserAccountId = 2,
                            UserPolicy = "EDIT PRODUCT"
                        },
                        new
                        {
                            Id = 8,
                            IsEnabled = false,
                            UserAccountId = 2,
                            UserPolicy = "DELETE_PRODUCT"
                        },
                        new
                        {
                            Id = 9,
                            IsEnabled = true,
                            UserAccountId = 3,
                            UserPolicy = "VIEW_PRODUCT"
                        },
                        new
                        {
                            Id = 10,
                            IsEnabled = true,
                            UserAccountId = 3,
                            UserPolicy = "ADD_PRODUCT"
                        },
                        new
                        {
                            Id = 11,
                            IsEnabled = true,
                            UserAccountId = 3,
                            UserPolicy = "EDIT PRODUCT"
                        },
                        new
                        {
                            Id = 12,
                            IsEnabled = true,
                            UserAccountId = 3,
                            UserPolicy = "DELETE_PRODUCT"
                        });
                });

            modelBuilder.Entity("PokemonDraft.Models.Pokedex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbilityA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbilityB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbilityC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Atk")
                        .HasColumnType("int");

                    b.Property<int>("Bst")
                        .HasColumnType("int");

                    b.Property<int>("Def")
                        .HasColumnType("int");

                    b.Property<int>("DexNum")
                        .HasColumnType("int");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Spa")
                        .HasColumnType("int");

                    b.Property<int>("Spd")
                        .HasColumnType("int");

                    b.Property<int>("Spe")
                        .HasColumnType("int");

                    b.Property<string>("Tier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeB")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pokedex");
                });
#pragma warning restore 612, 618
        }
    }
}
